version: 1.0.0
db: ${MONGO_DB}
venmoClientId: ${VENMO_CLIENT_ID}
venmoClientSecret: ${VENMO_CLIENT_SECRET}
sendGridUsername: ${SEND_GRID_USERNAME}
sendGridPassword: ${SEND_GRID_PASSWORD}
givingAppId: ${GIVING_APP_ID}
appDomain: ${APP_DOMAIN}
baseJustGivingFormUrl: ${BASE_JUST_GIVING_FORM_URL}
justGivingRedirectUrl: ${JUST_GIVING_REDIRECT_URL}
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${APPLICATION_PORT}
